const fortunes = [
  "The fortune you seek is in another cookie.",
  "A foolish man listens to his heart. A wise man listens to cookies.",
  "An alien of some sort will be appearing to you shortly.",
  "Do not mistake temptation for opportunity.",
  "He who laughs at himself never runs out of things to laugh at.",
  "Some men dream of fortunes, others dream of cookies.",
  "The greatest danger could be your stupidity.",
  "You will be hungry again in one hour.",
  "Because of your melodic nature, the moonlight never misses an appointment.",
  "Help! I am being held prisoner in a fortune cookie factory.",
  "It's about time I got out of that cookie.",
  "Only listen to the fortune cookie; disregard all other fortune telling units.",
  "It is a good day to have a good day.",
  "All fortunes are wrong except this one.",
  "Someone will invite you to a Karaoke party.",
  "That wasn't chicken.",
  "There is no mistake so great as that of being always right.",
  "No snowflake feels responsible in an avalanche.",
  "This cookie contains 117 calories.",
  "You think it's a secret, but they know.",
  "Change is inevitable, except for vending machines.",
  "Don't let statistics do a number on you.",
  "Never forget a friend. Especially if he owes you.",
  "Never wear your best pants when you go to fight for freedom.",
  "You love Chinese food.",
  "I am worth a fortune.",
  "A good way to keep healthy is to eat more Chinese food.",
  "Change can hurt, but it leads a path to something better.",
  "Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.",
  "You learn from your mistakes... You will learn a lot today.",
  "A fanatic is one who can't change his mind, and won't change the subject.",
  "If you look back, you'll soon be going that way.",
  "You will live long enough to open many fortune cookies.",
  "Flattery will go far tonight.",
  "We don't know the future, but here's a cookie."
];

module.exports = { fortunes };
